### ISSUE TITLE
[Suggestion] Make voxel shape exports more intuitive

### ISSUE THREAD

**Issue by ChloeDawn** [JannisX11/blockbench-plugins#118]
Within the UI it is not explained that elements used in a voxel shape export need to be grouped in a group named "VoxelShapes". Also, the resulting Java code may be confusing to new developers, as it does not create a `VoxelShape` but an `Optional<VoxelShape>`. I would suggest the following stream reduction format instead:
```java
// Take an empty shape as an identity
// Use the method that delegates to combineAndSimplify(a, b, OR)
// Return a VoxelShape rather than an Optional<VoxelShape>
.reduce(VoxelShapes.empty(), VoxelShapes::or);
```
Alternatively, Mojang already have a static helper that does this too!
```java
// Essentially Arrays.stream(varargs).reduce(firstArg, Shapes::or)
VoxelShapes.or(VoxelShapes.empty(), Block.createCuboidShape(...), Block.createC...);
```
(Fwiw this is how I discovered how to export a voxel shape when I had to Google it... Definitely needs to be clearer: https://www.reddit.com/r/Blockbench/comments/k3omsn/voxelshape_wont_export/?utm_source=ifttt)

**Comment by JannisX11** [comment]
@JTK222 have a look

**Comment by ChloeDawn** [comment]
In theory, the identity shape could just be the first shape of the element list, as although it is a root that others are OR'd with, if the model has an element larger than all it would eventually be OR'd to encompass that anyway? So the starting shape doesn't really matter. Therefore it could be exported simply as `VoxelShapes.or(...)` with each `createCuboidShape` in respective element order.

**Comment by JTK222** [comment]
I added a popup when you're missing the group.
But I am not going to change the export.
It supports more than just using OR as a binary operation.
Switching it to your approach would further complicate the export code.
