### ISSUE TITLE
[Mod Utils] Tabula imported models with mirroring not mirroring correctly

### ISSUE THREAD

**Issue by AzureDoom** [JannisX11/blockbench-plugins#123]
How it should look: 
![image](https://user-images.githubusercontent.com/7415711/104889264-f26b6880-593b-11eb-976d-712231c8d6ea.png)

After imported into Blockbench via Mod Utils.
![image](https://user-images.githubusercontent.com/7415711/104889255-ee3f4b00-593b-11eb-9116-0fcfe5eb324a.png)

Test Mode: 
[ICON_OF_SIN.zip](https://github.com/JannisX11/blockbench-plugins/files/5828752/ICON_OF_SIN.zip)

**Comment by cybercat5555** [comment]
Adding to this with a clearer example-- here's a mob for a mod in the works, note how the left leg and horn and right arm (from its perspective) are cybernetic
![Screenshot 2021-01-18 03 24 32](https://user-images.githubusercontent.com/17956808/104890321-6b1ef480-593d-11eb-8586-4fba5e501084.png)
also notice the name of this part
![Screenshot 2021-01-18 03 24 50](https://user-images.githubusercontent.com/17956808/104890348-740fc600-593d-11eb-8530-a8ce508a7941.png)
And when the model is imported into bb, it inverts the parts
![Screenshot 2021-01-18 03 25 54](https://user-images.githubusercontent.com/17956808/104890436-8c7fe080-593d-11eb-82ce-52199132af8f.png)
![Screenshot 2021-01-18 03 26 04](https://user-images.githubusercontent.com/17956808/104890443-8f7ad100-593d-11eb-8fce-1b796faeebab.png)

**Comment by JTK222** [comment]
Noted, will be fixed with the next update for Mod Utils.
