### ISSUE TITLE
[Plugin Request] Player Behavior Riding Editor/Viewer

### ISSUE THREAD

**Issue by StealthyExpertX** [JannisX11/blockbench-plugins#13]
Hey, I had an idea for a plugin that might be really useful but the issue is I'm not experienced enough with java script yet or the BlockBench Api to create it.

The idea is to have an editor that can add player riding positions and display them on the model maybe as transparent player models so they will display like so in the game you would be able to add more then 1 player seat to a model example would be say if you wanted a buss to have multiple of 10 seats it can be done and how it would export this is one of two ways, either a raw behavior component in a json file that the user can add to a behavior him / her self or by exporting a template behavior file that contains bare min needed behaviors with the riding behavior component, you would also be able to test and see how players can rotate on this using values such as lock player_rotation, rotate_player.

https://cdn.discordapp.com/attachments/341357554217123842/576047048395063346/BP.mcpack
This has a boat entity that shows the behavior being used for two players and rotates and locks their rotations.

**Comment by JannisX11** [comment]
Added in https://github.com/JannisX11/blockbench-plugins/commit/e17e37e7e0efb22cda468a1c431dd3c840696b58
