### ISSUE TITLE
[Plugin Request] Fix all duplicate bone names.

### ISSUE THREAD

**Issue by StealthyExpertX** [JannisX11/blockbench-plugins#14]
Example of use case: I have models that exported wrong where all bone names were reset to the same names so now I have models with 1000's of cubes that have all the same bone names and I need a quick easy plugin that would fix duplicate bone names by appending a number to the end of the bones name and checking if it exist or not?

**Comment by JannisX11** [comment]
A plugin to do this was now created by @bernie-g. In addition to that, in Blockbench 3.8 converting between different model formats will also make sure that bone names are unique.
