### ISSUE TITLE
[Bedrock Block Exporter]  add-on creation is broken on Linux

### ISSUE THREAD

**Issue by shizotoaster** [JannisX11/blockbench-plugins#162]
![image](https://user-images.githubusercontent.com/51480483/125161787-86611300-e1ae-11eb-8966-8ca55ae99e72.png)
Something is broken in creation of files' path

**Comment by JannisX11** [comment]
@Brennian The plugin currently uses backslashes for file paths, which only work on Windows. You can use the [Node path module](https://nodejs.org/api/path.html) to generate paths for the specific system that the block is on.
Example:
```javascript
PathModule.join('path', 'to', 'file.json');
```
