### ISSUE TITLE
[Issue] Geko lib deletes textures

### ISSUE THREAD

**Issue by AnMcreatorModDeveloper** [JannisX11/blockbench-plugins#196]
I used Gekolib to create an animation for someone's mod. At first, I had a modded entity but I changed the format to Animated Geko Lib Entity. After I save the model, I close Blockbench but then remember I forgot to download the texture (I needed to send the model to a friend, who's working on a mod). When I reopen the project the texture I spend 2 hours just vanished. What do I do?

Operating System: Windows 10
Blockbench: Application
Cause: Unknown

How it looks now:
![image](https://user-images.githubusercontent.com/95619375/144859025-3ca0782c-f7ce-4400-956a-85a0aa27e2a1.png)

How it is supposed to look:
![image](https://user-images.githubusercontent.com/95619375/144860301-ca98180c-7c50-4e1d-9508-dbced09a232d.png)

**Comment by JannisX11** [comment]
Save your project via File > Save Project in order to keep the texture, or save the texture individually. For more questions, please use the Blockbench or Geckolib Discord server (https://discord.gg/blockbench).
