### ISSUE TITLE
[Issue] Browse button doesn't work to import vanilla/custom assets folder

### ISSUE THREAD

**Issue by Legende04** [JannisX11/blockbench-plugins#197]
the button with which you should import the vanilla assets does nothing, and importing any structure is broken now

**Comment by Nevoska** [comment]
Same thing here. It used to work fine last time i tried!

**Comment by Nevoska** [comment]
![image](https://user-images.githubusercontent.com/20825228/147887749-7257ecb3-b540-4eed-8a7f-fd33f847fada.png)
This is the error on the console when i clock the Browse button
