### ISSUE TITLE
Geckolib interpolation option not showing up in new update

### ISSUE THREAD

**Issue by MrSirSquishy** [JannisX11/blockbench-plugins#223]
I use geckolib to animate, and geckolib has a really useful feature that allows you to interpolate different ease in, ease out, and ease in and out functions.(like cubic, bounce, quadratic, etc.) It's really useful for making complex animations, but in the new update the interpolation options have just disappeared completely. what's going on? 

![image](https://user-images.githubusercontent.com/82787823/161361092-dffa7cfd-89ca-4896-8dd1-f66fe730af24.png)

**Comment by JannisX11** [comment]
Fixed in https://github.com/JannisX11/blockbench-plugins/commit/5dfa996df4d4b16b1569f8a684a401228a895b19

**Comment by MrSirSquishy** [comment]
Your all absolute legends :).
