### ISSUE TITLE
[Suggestion] Trigger an event when completed loading project

### ISSUE THREAD

**Issue by MrCrayfish** [JannisX11/blockbench-plugins#237]
I am currently working on a plugin that requires code to be run after loading a project. I've looked at `setup_project` but that runs before parsing/loading of textures. If there is a way to already do this, let me know. This event is purely for efficiency sake ~~since I already have a solution but it's basically running the same one time code every time a new texture is loaded.~~

Thank you!

Edit: Turns out my solution doesn't work for all cases.

**Comment by JannisX11** [comment]
All codecs should have parse and parsed events, that run before and after a codec loads a file.
So, for bbmodel files, you can do
```Codecs.project.on('parsed', doStuff)```

Hope that helps!
