### ISSUE TITLE
Choppiness with Keyframe animation plugin

### ISSUE THREAD

**Issue by VincentHuto** [JannisX11/blockbench-plugins#259]
As shown  in this video 
https://streamable.com/hpc7s9

the bedrock to java keyframe animation plugin seems to get glitchy and choppy in higher PartDefinition count models, Ive tested animations on smaller mobs and they work fine but as complexity increases, as does the choppiness.

Im unaware if this is an issue with the plugin(seems unlikely) or Mojang's Keyframe system(more plausible as no mob was intended to be this level of detail).

**Comment by TelepathicGrunt** [comment]
I am noticing this too and it is now holding up my mod from releasing my new update. (last thing that has to be done for my update). I have an example and video to reproduce the issue if that helps:

https://user-images.githubusercontent.com/40846040/179399385-1bfbf526-cbc0-4e61-959a-27c8f1aa3fc6.mp4
Block bench bedrock model and texture: [bee_queen.zip](https://github.com/JannisX11/blockbench-plugins/files/9127663/bee_queen.zip)

**Comment by JannisX11** [comment]
@MatthewGreenspun Any idea if this is an issue with the plugin, or with Minecraft itself?

**Comment by VincentHuto** [comment]
I've talked to a few people and it sounds like this may be

**Comment by MatthewGreenspun** [comment]
> myself and others have hand converted the same animations with similar results

If you got the same results by hand converting the animation, there is likely not much I can do as the plugin simply automates this process. I'll try looking into the issue raised by @TelepathicGrunt where the plugin might be losing info when converting animations.

**Comment by TelepathicGrunt** [comment]
@MatthewGreenspun @VincentHuto I talked with Lukas and he figured out the issue. The plugin is exporting the keyframes not in chronological order all the time. Where it is out of order, the animation breaks. 

Broken animation export: https://paste.ee/p/GAEpU
Correctly ordered animation: https://paste.ee/p/T5sjX

Once I manually correctly the order, the animation is no longer choppy

**Comment by VincentHuto** [comment]
Ah interesting, wouldnt have guessed it, here I was thinking it was just some mojank code.

**Comment by VincentHuto** [comment]
![image](https://user-images.githubusercontent.com/30220432/179670441-7cf114a7-82b5-4273-8fa6-63650a1b9cbf.png)
Ive been doing some testing to try to track down why it may be doing them out of order, and simply logging the values time wise does confirm them being out of order within the for loops.

Ive since created a fixed version which I will pr that simply sorts the keyframes before they are formatted, which seems to work fine not super efficient but it seems to work.

Heres a streamable link with the fixed animation in action
https://streamable.com/fbmp4a

**Comment by VincentHuto** [comment]
Fixed with PR#262
