### ISSUE TITLE
Minecraft Block Wizard does not work

### ISSUE THREAD

**Issue by tomtom1969vlbg** [JannisX11/blockbench-plugins#322]
When I try to use the Minecraft Block Wizard everything is fine till I come to the last page "Next steps".
I can click "Next" there as often as I want but nothing happens.
I selected "integrate into Pack" as I created alredy one in Bridgev2.
This pack was shown atumaticel when I selcetd - so I used that.
Why?
When exporting to a folder, I can click the Next Button and work on the block - but not when I selcted to export into Pack.
Thanks in advance for helping
Thomas

**Comment by JannisX11** [comment]
Fixed in 1.2.0
