### ISSUE TITLE
Wont export to Minecraft after you updated program just now

### ISSUE THREAD

**Issue by curbs22** [JannisX11/blockbench-plugins#327]
### Detailed description of your issue

The program updated, now it wont export to Minecraft.

### Model format in which the issue occurs

Bedrock

### Blockbench variant

Program

### Operating System

Win11

**Comment by JannisX11** [comment]
This should be fixed now. It might take up to a few hours for the updated plugin to get to you.

**Comment by curbs22** [comment]
wow..thank u
