### ISSUE TITLE
Structure importer not seeing assets

### ISSUE THREAD

**Issue by Shroototem** [JannisX11/blockbench-plugins#33]
I select my ".nbt" structure file and the "assets" folder path, but when I confirm it says: "Error: File not found: blockstates\cobblestone.json"
The assets where extracted from the 1.14.4 client jar.

**Comment by ronthecookie** [comment]
Are you on a UNIX based OS? I have noticed similar issues

**Comment by lenover12** [comment]
I'm wondering if there is an easy resolution to this issue with it most likely being a file naming problem.
