### ISSUE TITLE
Fabric Modded Entity does not have Display Tab active && missing export json model

### ISSUE THREAD

**Issue by hellozyemlya** [JannisX11/blockbench-plugins#391]
Hi. First of all thanks a lot for a nice program.

For fabric modded entity there is no way to set display transformations. I can set them if I change model_format from "modded_entity" to "java_block" manually.

Also, there is no way to export fabric modded entity json part(with "parent": "builtin/entity" and transforms for display

**Comment by JannisX11** [comment]
Entity and Block/Item are two fundamentally different model formats. Entity models are not JSON based and don't have display settings.
