### ISSUE TITLE
Can't integrate into a specific pack on Minecraft Entity and Block Wizard.

### ISSUE THREAD

**Issue by FreddyIsHere25** [JannisX11/blockbench-plugins#396]
I'm currently trying to make an entity for Minecraft but when i try to integrate into pack. It doesn't let me export and continue. The same is happening with the Block Wizard but there i get stuck at the "Next Steps" Page.

It isn't working on that specific pack but in other packs it works normally. Before that i accidentaly modified the manifest and the pack went missing, then i recoved it. After that the whole issue happened.

**Blockbench Variant**
Program

**Operating System**
Windows 11

**Comment by JannisX11** [comment]
This is not an issue with the plugin itself, but with your pack. For example, your manifest file might have an incorrect name or incorrect formatting. Or the link to the connected resource pack is missing.
There are Discord servers about Minecraft Addon development where you could ask for help with that.
