### ISSUE TITLE
plugin browser doesn't work on desktop app

### ISSUE THREAD

**Issue by Dan1172010** [JannisX11/blockbench-plugins#407]
<img width="349" alt="image" src="https://github.com/JannisX11/blockbench-plugins/assets/141888991/90b21971-674f-4c6d-ad5c-fcb728ffa599">
i'm trying to download block wizzard but the browser returns no results @JannisX11  pls fix.

**Comment by Malik12tree** [comment]
I'm not aware of a plugin called "block wizzard", perhaps you meant "Minecraft Block Wizard"
