### ISSUE TITLE
Plugin browser won't load?

### ISSUE THREAD

**Issue by UsernameAdamGits** [JannisX11/blockbench-plugins#409]
So after installing blockbench, I was looking forward to install some plugins for minecraft stuff.
But the built-in plugin browser.... won't load?
Here are two images 
One showing the built-in plugin browser just not showing anything
And another one showing that the app wasn't able to connect the the plugin server (which is weird considering that I did give it firewall access).
![image](https://github.com/JannisX11/blockbench-plugins/assets/87935679/136bf7cf-4193-4a10-8b61-48774fcd63ae)
![image](https://github.com/JannisX11/blockbench-plugins/assets/87935679/6591872e-c428-45a5-b9c0-2acd852cf423)

**Comment by JannisX11** [comment]
Enable CDN Mirror in the Blockbench settings.

**Comment by UsernameAdamGits** [comment]
I can't find it in settings.
