### ISSUE TITLE
[Cardinal] Broken Plugin

### ISSUE THREAD

**Issue by Acaitart** [JannisX11/blockbench-plugins#447]
What plugin is supposed to do: show cardinal directions (n,s,e,w) while modeling

Current Behavior: Does not display at all, is not available in "view" or any other menu to toggle it on/off

Used to work in older versions, seems to be broken in version 4.8.3

**Comment by JannisX11** [comment]
@Bug1312

**Comment by Bug1312** [comment]
A temporary fix seems to be disabling and re-enabling the plugin in a project. 
I will be looking into the issue later today.
Thank you Jannis for mentioning me.
