### ISSUE TITLE
[Minecraft Title Generator]

### ISSUE THREAD

**Issue by iiiHERO** [JannisX11/blockbench-plugins#459]
I want to ask you if you can add thes things

Player name

Purple border

![Screenshot_20231101-160017_Chrome](https://github.com/JannisX11/blockbench-plugins/assets/154620417/d335c623-4b81-429e-ad17-7d13bf162930)

And button texts

![Pasted-20230815-181114](https://github.com/JannisX11/blockbench-plugins/assets/154620417/d533d3e4-055b-47a7-9181-68e657a06957)

Thanks for your hard work!

**Comment by ewanhowell5195** [comment]
I do not take suggestions.
If you want something added, you can read the guide on how to create them and then submit it to the plugin yourself:
https://github.com/ewanhowell5195/MinecraftTitleGenerator?tab=readme-ov-file#submissions
