### ISSUE TITLE
Enity wizard error

### ISSUE THREAD

**Issue by ROBOTICcreator** [JannisX11/blockbench-plugins#484]
I can not export entity into my game, Error: No installation of Minecraft bedrock edition was found on your computer. I already have Minecraft and bedrock edition, I play it sometimes.

**Comment by ROBOTICcreator** [comment]
i am new here btw, just looking for help

**Comment by JannisX11** [comment]
Which operating system are you using? Are you using regular bedrock edition, or the preview version, or education edition?

**Comment by ROBOTICcreator** [comment]
NM figured it out, I did not have bedrock installed I only had Java.
