### ISSUE TITLE
[Mine-imator Model Exporter] Empty file/model

### ISSUE THREAD

**Issue by Incorretc** [JannisX11/blockbench-plugins#491]
whenever I use your plugin to export my model and import it to mine-imator or modelbench they are empty

EDIT: I forgot to attach the texture

[wormlethal.zip](https://github.com/JannisX11/blockbench-plugins/files/14588704/wormlethal.zip)
![wormlethal](https://github.com/JannisX11/blockbench-plugins/assets/84988589/5bc6403d-a41f-4419-990e-eadd55091341)

**Comment by JannisX11** [comment]
The model is in deed empty. This is likely not an issue with the plugin, but with your model. Ensure that your model consists of supported elements (i.e. Cubes, element types like Meshes are not supported by Mine-Imator). Check that the respective elements are set to export (via "more outliner options").

**Comment by JannisX11** [comment]
If this did not help, please attach the original model file as .bbmodel.

**Comment by zakazakavova** [comment]
where can I download?
