### ISSUE TITLE
[Suggestion] Is there any way to optimization PE model with picture?

### ISSUE THREAD

**Issue by MikuSnow** [JannisX11/blockbench-plugins#52]
Like this:
![image](https://user-images.githubusercontent.com/7759441/77498737-598ace80-6e8b-11ea-9ff2-08b2092f93cb.png)

optimization to

![image](https://user-images.githubusercontent.com/7759441/77498812-7f17d800-6e8b-11ea-9359-69908342438b.png)

also optimization the picture.

**Comment by JannisX11** [comment]
This seems overly complicated to do and unnecessary, since you could just create the second shape right away.
