### ISSUE TITLE
Feature Request - Seat Position/Hitbox + Default player positions

### ISSUE THREAD

**Issue by TrickShow** [JannisX11/blockbench-plugins#526]
Honestly not sure if Seat Position + Hitbox is the right request space for this but since it already has player geo when riding I thought It would be the best place for this.

I would love to have the ability to display the default player model standing specifically so that we can position items in hand. IE if I add a custom weapon to the game this feature would allow me to position and rotate the player to get proper data to correlate ingame display of items in game such as: Scale of the item and/or Rotation of said item.

**Comment by JannisX11** [comment]
This is already supported in Blockbench: https://youtu.be/5gUTZoTSPgE?si=8mJ0JNSfWT3IFHIt&t=215
