### ISSUE TITLE
[GeckoLib Animation Utils]  The easings buttons are missing and the timeline window lags when selecting keyframes.

### ISSUE THREAD

**Issue by Gottor** [JannisX11/blockbench-plugins#548]
After the last blockbench update (4.10.2), the buttons for easings disappeared from the animation tab in the keyframe window. Also, when selecting individual keyframes that had previously been assigned easings, visual glitches are noticeable, as if the keyframe was not selected, but is selected after a few clicks.
![image](https://github.com/JannisX11/blockbench-plugins/assets/3237405/e73cc9b2-d631-4f38-813b-d04eb3eba780)

**Comment by JannisX11** [comment]
Fixed in #550
