### ISSUE TITLE
[CEM Template Loader] Trident model is broken?

### ISSUE THREAD

**Issue by diskree** [JannisX11/blockbench-plugins#566]
Hi, I noticed that if you import the trident model, its composition is different from other models. I mean, all 5 parts of the trident model are named as "body", but body is just one of the parts, it is oblong part of the trident. 

Also, according to the CEM documentation, the parts of the trident should be named: base, left_spike, middle_spike, right_spike. Only the 4 parts of the trident are listed here, but the "body" is missing altogether.

On whose side is the mistake? and is this a mistake at all?

**Comment by JannisX11** [comment]
@ewanhowell5195

**Comment by ewanhowell5195** [comment]
the model is outdated. the in game model changed somewhat recently and i need to update it

**Comment by ewanhowell5195** [comment]
This has been fixed

**Comment by diskree** [comment]
Thanks :)
