### ISSUE TITLE
[Suggestion] fabric entity model support

### ISSUE THREAD

**Issue by hYdos** [JannisX11/blockbench-plugins#73]
title says all

**Comment by fadookie** [comment]
I have an experimental plugin for fabric export but haven't had time to clean it up and publish it yet. I may add it to ModUtils when I get a chance.

You can try to "load from URL" here: https://gistcdn.githack.com/fadookie/8db7437479baaf34f76cd19283451050/raw/518fb23569f2d933406fdca3791adb1f0d6792cb/modded_entity_fabric.js

It adds some Fabric project types you can choose from the project settings window and export as normal. It also adds the ability to change some settings in the template like package name and entity type parameter.

GeckoLib also now has support for exporting animated Java models for fabric built into the plug-in, if you use our runtime library.

**Comment by JannisX11** [comment]
The aforementioned Farbic plugin is now public.
