### ISSUE TITLE
Tabula Imports no longer seem to work. [Issue]

### ISSUE THREAD

**Issue by IvorAmlug** [JannisX11/blockbench-plugins#83]
So I use the newest version of blockbench and the 1.15.2 version of tabula
I also have the plugin installed to convert .tbl files.
So ive tried to import my tbl model to a moddet entity and only got an empty folder called root that contains nothing

![Screenshot (11)](https://user-images.githubusercontent.com/38656481/89006512-38d5f800-d307-11ea-8707-3907c7cb9f59.png)

**Comment by JannisX11** [comment]
@JTK222 ^

**Comment by JTK222** [comment]
Afaik the save format changed in Tabula for 1.15.2 
I'll have to try and figure out what changed again.
I don't have much free time recently, and my private projects have a higher priority but I'll try to take a look at it at one point.
I'd appreciate if you'd have a .tbl file from 1.15 for me so I can't take a look at the format.

**Comment by IvorAmlug** [comment]
Of course i got one:
[Model.zip](https://github.com/JannisX11/blockbench-plugins/files/5010799/Model.zip)

**Comment by JTK222** [comment]
So I just look into it, and noticed that there is a new version tag.
To be specific we are already at version 5 of the tabula model format.
the 1.12 didn't have that version tag. So for now I'll add basic support for the 1.12 version and version 5, but for all inbetween I'll have to contact IChun as there is absolutely no info on the formats to be found.
