### ISSUE TITLE
GeckoLib | [Issue] Rotation space does not apply

### ISSUE THREAD

**Issue by ConnorTron110** [JannisX11/blockbench-plugins#84]
### Description
Normally on a Blockbench entity, when you make a bone, on the toolbar there are options on how to rotate:
Global, Local and Bone.

Normally you would expect the rotation type to apply, however in this case it doesn't.
No matter what, the rotation type always stays as Global which is highly frustrating when animating said entity.

### Steps to Reproduce
> Make a new **Animated Java Entity** 
> Make a simple body and a simple bone
> *For better example* Make the bone angled and its pivot point at the corner
> Rotate the bone at the Global Rotation option
> Rotate the bone at the Local Rotation option
> **Observe Major Frustration**

**Comment by fadookie** [comment]
@ConnorTron110 can you reproduce this behavior on a regular Modded Java Entity project? If so the issue is probably with blockbench core and not our plugin. However in some cases these issues may be due to vanilla limitations of entity format, I'm not sure.

**Comment by ConnorTron110** [comment]
Using a regular Java Entity and the same does not happen. *Was using the Local Rotation Space option*
![image](https://user-images.githubusercontent.com/39780128/89205751-1ca8b400-d5b0-11ea-915d-0a0aad3d3ada.png)

**Comment by ConnorTron110** [comment]
**Update:** The rotation space setting does apply when you edit the model.
But does not apply When animating the model.

**Comment by fadookie** [comment]
Interesting. This may be a plug-in issue then possibly. I'd imagine there may be some assumptions in the animation window that apply to bedrock but not java models.

**Comment by JannisX11** [comment]
Rotation space is only implemented for edit mode currently.

**Comment by ConnorTron110** [comment]
Any update on this?

**Comment by bernie-g** [comment]
This should be obsolete now that GeckoLib uses bedrock models.

**Comment by JannisX11** [comment]
I think the issue is about rotation space in animation mode. But yeah, this would be a core Blockbench feature request, not a GeckoLib plugin issue, so it can be closed.
